# Generated by Django 2.1.7 on 2019-08-08 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190808_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='gate_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
