# Generated by Django 2.1.7 on 2019-08-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_gate_gate_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='gate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
